services:
  test:
    build: 
      context: ./test
      dockerfile : Dockerfile
    volumes:
    - ./tests:/tests
  app:
    build: 
      context: .
      dockerfile : Dockerfile
    volumes:
    - ./app:/app
    ports:
    - "80:80"
