services:
  test:
    build: 
      context: .
      dockerfile : Dockerfile.demo
    volumes:
    - ./tests:/tests
  app:
    build: 
      context: .
      dockerfile : Dockerfile
    volumes:
    - ./app:/app
    ports:
    - "80:80"
